name: Release

# Run the workflow when a Pull Request is opened or when changes are pushed to master
on:
 pull_request:
 push:
  branches: [ master ]

jobs:
 release:
  # Only release on push to master
  if: github.event_name == 'push' && github.ref == 'refs/heads/master'
  runs-on: ubuntu-latest
  # Waits for test jobs for each Node.js version to complete
  steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Setup Node.js
    uses: actions/setup-node@v1
    with:
      node-version: 14.x

  - name: Install
    run: yarn install --frozen-lockfile

  - name: Release
    run: npx semantic-release
  env:
    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}